### PR TITLE
Update to latest dependencies versions

### LINKED ISSUE #1: cargo run results in "build failed"
Heyo, I know this is an old project but I'm getting this error when running `cargo run` for the first time

```
Compiling glium v0.16.0
error: type `color_space::__CGColorSpace` is private

[I removed 56 other error messages here]

error: could not compile `cocoa`
error: build failed
```

I'm not familiar with the Rust ecosystem, is there an easy fix for this?

### PR DESCRIPTION
**Pull request by emigr2k1**
This commit pins to the latest dependencies versions (removing the
wildcard versions from Cargo.toml).

This fixes compiling errors on MacOS too.

This commit just updates the code to make it work and does not perform
any refactoring. Code should be cleaned.

Fixes #1

### CODE REVIEW

**Comment by emigr2k1** [comment]
Enabling vsync in the ContextBuilder makes the checkers example run very slow when you drag the board. It's not obvious to me why this happens. In this commit I didn't enable vsync but I guess we would want to enable vsync.

Edit: I was doing it wrong. I was drawing in the event loop closure but this closure runs for every event. I had to ask for a redraw event and draw when this redraw event fires. I added a commit to add vsync.

Edit 2: Nevermind. I think the order should be:

- On start event:
    - Draw
    - Schedule redraw event within 16.6666 ms
- On window/input event
    - Push event to vector of events
- On redraw event:
    - Re-draw
    - Handle events
    - Schedule redraw within 16.6666 ms

**Comment by mfs** [comment]
Wow. Awesome. I'm going to merge this as is. I wrote this a long time ago and the existing code was pretty meh. It probably all needs a clean up anyway.

**Comment by emigr2k1** [comment]
@mfs I just noticed I changed the key to reload the shader from 'F5' to 'r'. Do you want me to send another pr or is it fine?

I did this because my 'F' keys don't work and forgot to change it back.

**Comment by mfs** [comment]
Ah, it's fine. I'll make it so both <F5> and 'r' do a reload. Might be handy for someone else.

**Pull request merged**
